version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"  # Map host port to container port
    volumes:
      - .:/app       # Mount the local directory into the container
    env_file:
      - .env         # Load environment variables from the .env file
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Map host port to container port
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
